name: ultrack-stardist
channels:
  - conda-forge
  - rapidsai
  - defaults
  - gurobi
dependencies:
  - python=3.10
  - rapidsai::cucim
  - conda-forge::cudatoolkit=11.2
  - conda-forge::cudnn=8.4.1
  - conda-forge::tensorflow-gpu=2.11.0
  - conda-forge::cupy
  - coin-or-cbc
  - gurobi
  - jupyter
  - pytorch
  - pip
  - zarr
  - pip:
    - pyqt5
    - napari
    - stardist
    - csbdeep
