name: ultrack-multi-color
channels:
  - gurobi
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - cellpose
  - coin-or-cbc
  - cucim
  - cupy!=13.0.*
  - gurobi
  - jupyter
  - pip
  - pyqt
  - seaborn
  - pip:
    - napari==0.4.18
    - traccuracy
    - napari-arboretum
    - pyift
